[[unifi-controller]]
alias    = "local"
url      = "https://192.168.1.2:8443"
insecure = true
username = "admin"
password = "password"

[[unifi-controller]]
alias    = "remote"
url      = "https://unifi.example.com"
username = "admin"
password = "topsecret"
