project_name: unifi-sdn-exporter

builds:
- goos:   [linux]
  goarch: [amd64]
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -X main.version={{.Version}} -X main.commit={{.Commit}}

nfpms:
  - formats: [deb]
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor:       Digineo GmbH
    homepage:     https://www.digineo.de/
    maintainer:   Julian Kornberger <jk+github@digineo.de>
    description:  Prometheus Exporter for Unifi SDN Controllers
    license:      Apache 2.0
    section:      default
    priority:     extra

    bindir: /usr/bin
    contents:
      - src: debian/unifi-sdn-exporter.service
        dst: /lib/systemd/system/unifi-sdn-exporter.service

      - src: debian/default
        dst: /etc/default/unifi-sdn-exporter
        type: config

      - src: exporter/config.example.toml
        dst: /etc/unifi-sdn-exporter/config.toml
        type: config
        file_info:
          mode: 0600
          owner: prometheus
          group: prometheus

    scripts:
      postinstall:  debian/postinstall.sh
      preremove:    debian/preremove.sh
      postremove:   debian/postremove.sh
